## Overview:

The LLM-based application simplifies and improves HR processes by using Language, Logic, and Machine Learning. It leverages Natural Language Processing, machine learning, and analytics to enhance efficiency, effectiveness, and decision-making in HR operations.

This user-friendly, scalable, and customizable application integrates with existing HR systems and tools, ensuring smooth data flow and compatibility. Its ultimate goal is to optimize HR processes, minimize manual efforts, enhance decision-making, and improve the employee experience.

## Task:

## 1. Input: Accept job descriptions and multiple CVs in various formats.

### **Job Description evaluation**
- Score the job description based on the job title, and provide recommendations for enhancements
- Give the user the option to either continue with the original version or incorporate the suggested changes

### **CV ranking**
- Rank the CVs according to their alignment with the job requirements and shortlist candidates
- Provide additional information on the shortlisted candidates

### **Email notifications:**
- Send emails to the shortlisted candidates, informing them about the next steps in the hiring process

### **Screening questions**
- Develop screening questions for each candidate, considering different levels of importance or significance assigned to the job description and the candidate's CV

### **First-round interview**
- Conduct the first round of interview
- Record the candidate's responses to the screening questions
- Evaluate their performance for consideration in the next in-person round

### **Communication**
- Maintain continuous communication with the HR team
- Providing updates on the hiring process and relevant information throughout
